name: novelx-env
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python=3.6
  - velvet
  - spades
  - samtools
  - quast
  - snakemake
  - blast
variables:
  LANG: en_US.utf-8
  LC_ALL: en_US.utf-8

