name: novelx-env
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python>=3.9
  - velvet
  - spades
  - samtools
  - quast
  - snakemake>=7.0
  - blast
variables:
  LANG: en_US.utf-8
  LC_ALL: en_US.utf-8

